#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Doit\Executer;
use Symfony\Component\Console\Input\ArgvInput;

use Symfony\Component\Yaml\Exception\ParseException;
use Symfony\Component\Yaml\Yaml;

try {
    $value = Yaml::parseFile(__DIR__.'/do-it.yml',Yaml::PARSE_CUSTOM_TAGS);
} catch (ParseException $exception) {
    printf('Unable to parse the YAML string: %s', $exception->getMessage());
}

$input = new ArgvInput();

$executer = new Executer($value);
$executer->execute($input);
